apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "segway-system.logpaths.fullname" . }}
  labels:
    {{- include "segway-system.logpaths.labels" . | nindent 4 }}
spec:
  {{- if not .Values.logpaths.autoscaling.enabled }}
  replicas: {{ .Values.logpaths.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "segway-system.logpaths.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.logpaths.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "segway-system.logpaths.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.logpaths.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "segway-system.logpaths.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.logpaths.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.logpaths.securityContext | nindent 12 }}
          image: "{{ .Values.logpaths.image.repository }}:{{ .Values.logpaths.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logpaths.image.pullPolicy }}
          env:
            - name: SYSLOG_DESTINATION_SERVICE_NAME
              value: 
          ports:
            - name: syslog-tcp
              containerPort: {{ .Values.logpaths.service.port }}
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/syslog-ng/
            name: cache-volume       
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.logpaths.resources | nindent 12 }}
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi                   
      {{- with .Values.logpaths.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logpaths.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logpaths.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
