apiVersion: v1
kind: Service
metadata:
  name: {{ include "segway-system.logpaths.fullname" . }}
  labels:
    {{- include "segway-system.logpaths.labels" . | nindent 4 }}
spec:
  type: {{ .Values.logpaths.service.type }}
  ports:
    - port: {{ .Values.logpaths.service.port }}
      targetPort: syslog-tcp
      protocol: TCP
      name: syslog-tcp
  selector:
    {{- include "segway-system.logpaths.selectorLabels" . | nindent 4 }}
