{{- if .Values.logpaths.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "segway-system.logpaths.serviceAccountName" . }}
  labels:
    {{- include "segway-system.logpaths.labels" . | nindent 4 }}
  {{- with .Values.logpaths.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
