{{- if .Values.destinations.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "segway-system.serviceAccountName" . }}
  labels:
    {{- include "segway-system.destinations.labels" . | nindent 4 }}
  {{- with .Values.destinations.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
